# Generated by Django 2.0.6 on 2018-06-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20180618_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
